"""Phase 7 - generate the full code listing appendix.

The report format requires an "Appendix: Full code listing". Rather than paste
several thousand lines into the report body, this renders every source file
into docs/APPENDIX_CODE.md so the appendix can be regenerated and stays in sync.

Run:  python src/export_appendix.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "APPENDIX_CODE.md"

# (relative path, one-line role). Order is the reading order of the pipeline.
FILES: list[tuple[str, str]] = [
    ("src/config.py", "Single source of truth: sampling interval, thresholds, valid ranges"),
    ("src/data_generator.py", "Simulates the 2016-row dataset with labelled occupancy and injected faults"),
    ("src/preprocessing.py", "Validation, hour feature, chronological split, leakage checks"),
    ("src/modeling.py", "Cross-validated tuning, fits, scoring, confusion matrices"),
    ("src/detection.py", "Rolling Z-score, flatline range rules, sensor health"),
    ("src/control_logic.py", "Lighting and HVAC decisions, fail-safe gating"),
    ("src/phase5_run.py", "Historical replay driver -> data/control_output.csv"),
    ("src/dashboard_data.py", "Inference-only metrics, filters, serial parsing"),
    ("app.py", "Streamlit dashboard, four tabs"),
    ("src/architecture_diagram.py", "Renders docs/architecture.png"),
    ("src/final_audit.py", "Phase 7 functional / regression / documentation audit"),
    ("src/export_appendix.py", "Generates this listing"),
    ("src/export_report_docx.py", "Converts the report to .docx"),
    ("src/main.cpp", "ESP32 firmware: sensors, threshold control, serial output"),
    ("sketch.ino", "Byte-identical Wokwi copy of the firmware"),
    ("tests/test_control_logic.py", "Control truth table + flatline unit tests"),
    ("tests/test_phase5_replay.py", "Replay schema, safety invariants, determinism"),
    ("tests/test_dashboard.py", "Dashboard acceptance tests"),
    ("platformio.ini", "Firmware build configuration"),
    ("wokwi.toml", "Wokwi simulation configuration"),
    ("requirements.txt", "Pinned Python dependencies"),
]

HEADER = """# Appendix - Full Code Listing

*Generated by `python src/export_appendix.py`. Do not edit by hand.*

Team 8 - Occupancy-Based Lighting/HVAC
Using Machine Learning.

| # | File | Lines | Role |
| --- | --- | --- | --- |
"""


def main() -> int:
    rows: list[str] = []
    parts: list[str] = [HEADER]
    missing: list[str] = []
    total = 0

    for index, (relative, role) in enumerate(FILES, start=1):
        path = ROOT / relative
        if not path.exists():
            missing.append(relative)
            continue
        text = path.read_text(encoding="utf-8")
        count = len(text.splitlines())
        total += count
        lang = "cpp" if path.suffix in {".cpp", ".ino"} else (
            "ini" if path.suffix == ".ini" else (
                "toml" if path.suffix == ".toml" else "python"
            )
        )
        rows.append(f"| {index} | `{relative}` | {count} | {role} |")
        fence = "cpp" if lang == "cpp" else ("text" if lang in {"ini", "toml"} else "python")
        parts.append(
            f"\n---\n\n## {relative}\n\n{role} — {count} lines.\n\n"
            f"```{fence}\n{text.rstrip()}\n```\n"
        )

    table = "\n".join(rows) + f"\n| | **Total** | **{total}** | |\n"
    parts.insert(1, table)

    if missing:
        parts.append(
            "\n### Not found at generation time\n\n"
            + "\n".join(f"- `{m}`" for m in missing)
            + "\n"
        )

    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size} bytes, {total} code lines)")
    if missing:
        print("WARNING missing:", ", ".join(missing))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
